### ISSUE TITLE
Building rtems-libbsd doesn't work from a fresh checkout

### ISSUE THREAD

**Issue by peerst** [grisp/grisp-software#1]
The reason is that there is the sequence

```
waf clean
waf configure
```

in the build script, but `waf clean` doesn't work if it was never configured.

Workaround:  on the first run after a fresh checkout comment out `waf clean` in 
`build/build-libbsd.sh`

**Comment by peerst** [comment]
Didn't run into this one last time I tried.  Is this fixed?

**Comment by c-mauderer** [comment]
Only insofar that the "waf clean" is commented. That works fine on a fresh checkout but might make problems on an RTEMS update. It is possible that the libbsd build system does not recognize a changed rtems header correctly and therefore forgets to rebuild some files. So it's now the other way round: It certainly works well on a fresh checkout but it might fail on an update.

**Comment by peerst** [comment]
Fixed by checking if wscript exists before calling waf clean

**Comment by peerst** [comment]
This fix seems not to have worked, just happened again

**Comment by c-mauderer** [comment]
Should be fixed by f40d6fcd65.
