### ISSUE TITLE
Install missing prerequisite: waf

### ISSUE THREAD

**Issue by c-mauderer** [grisp/grisp-software#4]
The build-scripts should install waf too.

**Comment by eproxus** [comment]
Is there a bin folder somewhere in the repo where `waf` could be included? It's just a 100K binary so it could be checked in directly even

**Comment by c-mauderer** [comment]
It should be a python script and not even a binary. Maybe we could put it into the `build/src` and copy it from there to the `rtems-install`?

**Comment by eproxus** [comment]
True, I meant "executable". I'm not familiar enough with the structure of the rtems build system and this repository to have any opinion about where to place it, other than that checking it in if possible is a nice solution because then it doesn't have to be installed by users

**Comment by eproxus** [comment]
Nice! Thanks!
