### ISSUE TITLE
RTEMS source builder prerequisites instructions not working

### ISSUE THREAD

**Issue by eproxus** [grisp/grisp-software#7]
The prerequisite *"to check for some of RTEMS source builders prerequisites"* cannot be performed because the folder `rtems-source-builder` is empty upon initial checkout.

**Comment by eproxus** [comment]
Just noticed that the check is automatically performed in `./build/build-toolchain.sh`. Perhaps it can be removed from the README?

**Comment by c-mauderer** [comment]
Hello @eproxus,

this relates to #5: The check runs a little late in the build process (after the long downloads). It would be better to move it further to the top. I planned to remove the lines from the README as soon as #5 is fixed.

**Comment by c-mauderer** [comment]
I think that #5 will need some more time. So I improved the description in the README that it at least works that way.
